# Generated by Django 3.1 on 2020-10-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionstore', '0002_auto_20201021_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('price', models.FloatField()),
                ('delprice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InspiredProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('price', models.FloatField()),
                ('delprice', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='delprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(),
        ),
    ]
