# Generated by Django 3.1 on 2020-10-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionstore', '0003_auto_20201021_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('date', models.DateTimeField()),
                ('blogimage', models.ImageField(upload_to='img')),
            ],
        ),
    ]
