# Generated by Django 3.1 on 2020-10-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionstore', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('Featured Products', 'Featured Products'), ('New Products', 'New Products'), ('Inspired Products', 'Inspired Products')], default=0, max_length=200),
            preserve_default=False,
        ),
    ]
