# Generated by Django 3.1 on 2020-10-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionstore', '0005_products_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedProducts',
        ),
        migrations.DeleteModel(
            name='InspiredProducts',
        ),
    ]
