# Generated by Django 3.1 on 2020-10-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionstore', '0008_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_name', models.CharField(max_length=100)),
                ('cart_img', models.ImageField(upload_to='img')),
                ('cart_price', models.FloatField()),
            ],
        ),
    ]
