# Generated by Django 3.1 on 2020-10-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionstore', '0009_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
