# Generated by Django 3.1 on 2020-10-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionstore', '0010_auto_20201029_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_price',
            field=models.FloatField(null=True),
        ),
    ]
