# Generated by Django 3.1 on 2020-10-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionstore', '0011_auto_20201029_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(null=True),
        ),
    ]
